package com.hirehub.hirehub_backend.dto;

import com.hirehub.hirehub_backend.entity.Job;
import com.hirehub.hirehub_backend.enums.JobStatus;
import com.hirehub.hirehub_backend.enums.ShiftTiming;
import com.hirehub.hirehub_backend.enums.WorkMode;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class JobDto {
    private Long id;
    private String jobTitle;
    private String company;
    private List<ApplicantDto> applicants;
    private String about;
    private String experience;
    private String jobType;
    private String location;
    private Long packageOffered;
    private String description;
    private List<String> skillsRequired;
    private JobStatus jobStatus;
    private Long postedBy;
    private String category; // Industry/Category of the job
    private WorkMode workMode;
    private LocalDateTime applicationDeadline;
    private Integer numberOfOpenings;
    private ShiftTiming shiftTiming;

    public Job toEntity()
    {
        Job job = new Job();
        job.setId(this.id);
        job.setJobTitle(this.jobTitle);
        job.setCompany(this.company);
        job.setApplicants(this.applicants != null ? this.applicants.stream().map(ApplicantDto::toEntity).toList() : null);
        job.setAbout(this.about);
        job.setExperience(this.experience);
        job.setJobType(this.jobType);
        job.setLocation(this.location);
        job.setPackageOffered(this.packageOffered);
        job.setDescription(this.description);
        job.setSkillsRequired(this.skillsRequired);
        job.setJobStatus(this.jobStatus);
        job.setPostedBy(this.postedBy);
        job.setCategory(this.category);
        job.setWorkMode(this.workMode);
        job.setApplicationDeadline(this.applicationDeadline);
        job.setNumberOfOpenings(this.numberOfOpenings);
        job.setShiftTiming(this.shiftTiming);
        // createdAt is auto-generated by @CreationTimestamp, so we don't set it
        return job;
    }

}
